$(function(){
    $(".login").click(function(){
        $(".close").show();
    })
    $(".closex").click(function(){
        $(".close").hide();
    })
})
$(function(){
    $(".wxlogin").click(function(){
        $(".wx").show();
        $(".close").hide();
    })
    $(".closex").click(function(){
        $(".wx").hide();
    })
})